#!/bin/bash
export MSYS_NO_PATHCONV=1
export DOCKERHOST=${APPLICATION_URL-$(docker run --rm --net=host codenvy/che-ip)}
set -e

S2I_EXE=s2i
if [ -z $(type -P "$S2I_EXE") ]; then
  echo -e "The ${S2I_EXE} executable is needed and not on your path."
  echo -e "It can be downloaded from here: https://github.com/openshift/source-to-image/releases"
  echo -e "Make sure you extract the binary and place it in a directory on your path."
  exit 1
fi

SCRIPT_HOME="$(cd "$(dirname "$0")" && pwd)"

# =================================================================================================================
# Usage:
# -----------------------------------------------------------------------------------------------------------------
usage() {
  cat <<-EOF

      Usage: $0 [command] [options]

      Commands:

      up -  Builds the images, creates the application containers
            and starts the services based on the docker-compose.yml file.

            You can pass in a list of containers to start.
            By default all containers will be started.

            The API_URL used by tob-web can also be redirected.

            Examples:
            $0 start
            $0 start VERIFIER-agent

      start - Same as up

      restart - Re-starts the application containers,
                useful when updating one of the container images during development.

            You can pass in a list of containers to be restarted.
            By default all containers will be restarted.

            Examples:
            $0 start
            $0 start faber-agent

      logs - Display the logs from the docker compose run (ctrl-c to exit).

      stop - Stops the services.  This is a non-destructive process.  The volumes and containers
             are not deleted so they will be reused the next time you run start.

      down - Brings down the services and removes the volumes (storage) and containers.
      rm - Same as down


EOF
  exit 1
}
# -----------------------------------------------------------------------------------------------------------------
# Default Settings:
# -----------------------------------------------------------------------------------------------------------------
# TBD
DEFAULT_CONTAINERS="ngrok-hospital hospital-agent ngrok-manufacturer manufacturer-agent ngrok-seller seller-agent ngrok-medical_device_computer medical_device_computer-agent hospital-notebook manufacturer-notebook seller-notebook medical_device_computer-notebook"

# -----------------------------------------------------------------------------------------------------------------
# Functions:
# -----------------------------------------------------------------------------------------------------------------
function echoRed() {
  _msg=${1}
  _red='\e[31m'
  _nc='\e[0m' # No Color
  echo -e "${_red}${_msg}${_nc}"
}

function echoYellow() {
  _msg=${1}
  _yellow='\e[33m'
  _nc='\e[0m' # No Color
  echo -e "${_yellow}${_msg}${_nc}"
}

configureEnvironment() {

  if [ -f .env ]; then
    while read line; do
      if [[ ! "$line" =~ ^\# ]] && [[ "$line" =~ .*= ]]; then
        export ${line//[$'\r\n']/}
      fi
    done <.env
  fi

  for arg in "$@"; do
    # Remove recognized arguments from the list after processing.
    shift

    # echo "arg: ${arg}"
    # echo "Remaining: ${@}"

    case "$arg" in
    *=*)
      # echo "Exporting ..."
      export "${arg}"
      ;;
    *)
      # echo "Saving for later ..."
      # If not recognized, save it for later procesing ...
      set -- "$@" "$arg"
      ;;
    esac
  done

  # global
  export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:controller}"
  export GENESIS_URL="https://raw.githubusercontent.com/sovrin-foundation/sovrin/stable/sovrin/pool_transactions_builder_genesis"
  export WALLET_TYPE="indy"

  # TBD
  # hospital-agent
  export HOSPITAL_AGENT_NAME="HOSPITAL"
  export HOSPITAL_ADMIN_PORT=8071
  export HOSPITAL_HTTP_PORT=8070
  export HOSPITAL_WEBHOOK_PORT=8072
  export HOSPITAL_WEBHOOK_URL=${HOSPITAL_WEBHOOK_URL:-http://$DOCKERHOST:$HOSPITAL_WEBHOOK_PORT}
  export HOSPITAL_AGENT_ENDPOINT=${HOSPITAL_AGENT_ENDPOINT:-http://$DOCKERHOST:$HOSPITAL_HTTP_PORT}
  export HOSPITAL_WALLET_SEED="HAGENT_seed_00000000000000000000"
  export HOSPITAL_WALLET_KEY="HOSPITAL_key_00000000000000000000000"
  export HOSPITAL_WALLET_NAME="HOSPITAL Wallet"
  export HOSPITAL_JUPYTER_PORT="8889"
  export HOSPITAL_ADMIN_SECURE="true"

  # manufacturer-agent
  export MANUFACTURER_AGENT_NAME="MANUFACTURER"
  export MANUFACTURER_ADMIN_PORT=8051
  export MANUFACTURER_HTTP_PORT=8050
  export MANUFACTURER_WEBHOOK_PORT=8052
  export MANUFACTURER_WEBHOOK_URL=${MANUFACTURER_WEBHOOK_URL:-http://$DOCKERHOST:$MANUFACTURER_WEBHOOK_PORT}
  export MANUFACTURER_AGENT_ENDPOINT=${MANUFACTURER_AGENT_ENDPOINT:-http://$DOCKERHOST:$MANUFACTURER_HTTP_PORT}
  export MANUFACTURER_WALLET_SEED="MAGENT_seed_00000000000000000000"
  export MANUFACTURER_WALLET_KEY="MANUFACTURER_key_00000000000000000000000"
  export MANUFACTURER_WALLET_NAME="MANUFACTURER Wallet"
  export MANUFACTURER_JUPYTER_PORT="8888"
  export MANUFACTURER_ADMIN_SECURE="true"

  # seller-agent
  export SELLER_AGENT_NAME="SELLER"
  export SELLER_ADMIN_PORT=8021
  export SELLER_HTTP_PORT=8020
  export SELLER_WEBHOOK_PORT=8022
  export SELLER_WEBHOOK_URL=${ISSUER_WEBHOOK_URL:-http://$DOCKERHOST:$SELLER_WEBHOOK_PORT}
  export SELLER_AGENT_ENDPOINT=${SELLER_AGENT_ENDPOINT:-http://$DOCKERHOST:$SELLER_HTTP_PORT}
  export SELLER_WALLET_SEED="SAGENT_seed_00000000000000000000"
  export SELLER_WALLET_KEY="SELLER_key_00000000000000000000000"
  export SELLER_WALLET_NAME="SELLER Wallet"
  export SELLER_JUPYTER_PORT="8890"
  export SELLER_ADMIN_SECURE="true"

  # medical_device_computer-agent
  export MEDICAL_DEVICE_COMPUTER_AGENT_NAME="MEDICAL_DEVICE_COMPUTER"
  export MEDICAL_DEVICE_COMPUTER_ADMIN_PORT=7991
  export MEDICAL_DEVICE_COMPUTER_HTTP_PORT=7990
  export MEDICAL_DEVICE_COMPUTER_WEBHOOK_PORT=7992
  export MEDICAL_DEVICE_COMPUTER_WEBHOOK_URL=${MEDICAL_DEVICE_COMPUTER_WEBHOOK_URL:-http://$DOCKERHOST:$MEDICAL_DEVICE_COMPUTER_WEBHOOK_PORT}
  export MEDICAL_DEVICE_COMPUTER_AGENT_ENDPOINT=${MEDICAL_DEVICE_COMPUTER_AGENT_ENDPOINT:-http://$DOCKERHOST:$MEDICAL_DEVICE_COMPUTER_HTTP_PORT}
  export MEDICAL_DEVICE_COMPUTER_WALLET_SEED="DAGENT_seed_00000000000000000000"
  export MEDICAL_DEVICE_COMPUTER_WALLET_KEY="MEDICAL_DEVICE_COMPUTER_key_00000000000000000000000"
  export MEDICAL_DEVICE_COMPUTER_WALLET_NAME="MEDICAL_DEVICE_COMPUTER Wallet"
  export MEDICAL_DEVICE_COMPUTER_JUPYTER_PORT="8891"
  export MEDICAL_DEVICE_COMPUTER_ADMIN_SECURE="true"


}

getInputParams() {
  ARGS=""

  for arg in $@; do
    case "$arg" in
    *=*)
      # Skip it
      ;;
    *)
      ARGS+=" $arg"
      ;;
    esac
  done

  echo ${ARGS}
}

getStartupParams() {
  CONTAINERS=""
  ARGS=""

  for arg in $@; do
    case "$arg" in
    *=*)
      # Skip it
      ;;
    -*)
      ARGS+=" $arg"
      ;;
    *)
      CONTAINERS+=" $arg"
      ;;
    esac
  done

  if [ -z "$CONTAINERS" ]; then
    CONTAINERS="$DEFAULT_CONTAINERS"
  fi

  echo ${ARGS} ${CONTAINERS}
}

deleteVolumes() {
  _projectName=${COMPOSE_PROJECT_NAME:-docker}

  echo "Stopping and removing any running containers ..."
  docker-compose down -v

  _pattern="^${_projectName}_\|^docker_"
  _volumes=$(docker volume ls -q | grep ${_pattern})

  if [ ! -z "${_volumes}" ]; then
    echo "Removing project volumes ..."
    echo ${_volumes} | xargs docker volume rm
  else
    echo "No project volumes exist."
  fi

  echo "Removing build cache ..."
  rm -Rf ../client/tob-web/.cache
}


getSeedJson() {
  _seed=${1}
  if [ -z "${_seed}" ]; then
    echo -e \\n"getSeedJson; Missing parameter!"\\n
    exit 1
  fi

  echo "{\"seed\": \"${_seed}\"}"
}

generateSeeds() {
  echo ${INDY_WALLET_SEED}
}



toLower() {
  echo $(echo ${@} | tr '[:upper:]' '[:lower:]')
}

echoError() {
  _msg=${1}
  _red='\033[0;31m'
  _nc='\033[0m' # No Color
  echo -e "${_red}${_msg}${_nc}" >&2
}

functionExists() {
  (
    if [ ! -z ${1} ] && type ${1} &>/dev/null; then
      return 0
    else
      return 1
    fi
  )
}
# =================================================================================================================

pushd "${SCRIPT_HOME}" >/dev/null
COMMAND=$(toLower ${1})
shift || COMMAND=usage

case "${COMMAND}" in
start | up)
  echoYellow "Starting up... This can take a couple of minutes."
  _startupParams=$(getStartupParams $@)
  configureEnvironment "$@"
  docker-compose\
  --log-level ERROR up \
  --build --remove-orphans \
  -d ${_startupParams}
  docker-compose \
  --log-level ERROR logs \
  -f
  ;;
restart)
  _startupParams=$(getStartupParams $@)
  configureEnvironment "$@"
  docker-compose stop ${_startupParams}
  docker-compose up -d --build --remove-orphans ${_startupParams}
  ;;
logs)
  configureEnvironment "$@"
  docker-compose logs -f
  ;;
stop)
  configureEnvironment
  docker-compose stop
  ;;
rm | down)
  configureEnvironment
  docker-compose \
  --log-level ERROR down \
  -v
  usage
  ;;
esac

popd >/dev/null
